import type { Metadata } from "next";
import Navbar from "../components/ui/navbar/Navbar";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
